# Generated by Django 6.0.2 on 2026-05-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.PositiveIntegerField()),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cuotas', to='pagos.factura')),
            ],
        ),
    ]
