# Generated by Django 6.0.2 on 2026-03-03 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motor', models.CharField(max_length=100)),
                ('transmision', models.CharField(max_length=50)),
                ('tipo_combustible', models.CharField(max_length=50)),
                ('cilindraje', models.PositiveIntegerField(help_text='centimetros cubicos')),
                ('numero_chasis', models.CharField(max_length=100, unique=True)),
                ('numero_motor', models.CharField(max_length=100, unique=True)),
                ('capacidad_pasajeros', models.PositiveIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='info_tecnica', to='clientes_inventario.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('kilometraje', models.PositiveIntegerField()),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('taller', models.CharField(max_length=100)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='clientes_inventario.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='PropietarioAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='clientes_inventario.vehiculo')),
            ],
        ),
    ]
