# Generated by Django 6.0.2 on 2026-03-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotizaciones',
            new_name='Cotizacion',
        ),
        migrations.RenameModel(
            old_name='Reservas',
            new_name='Reserva',
        ),
        migrations.RenameModel(
            old_name='Ventas',
            new_name='Venta',
        ),
    ]
