# Generated by Django 6.0.2 on 2026-05-07 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0002_rename_cotizaciones_cotizacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cotizacion',
            new_name='Cotizaciones',
        ),
        migrations.RenameModel(
            old_name='Reserva',
            new_name='Reservas',
        ),
        migrations.RenameModel(
            old_name='Venta',
            new_name='Ventas',
        ),
    ]
