# Generated by Django 6.0.2 on 2026-05-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0003_rename_cotizacion_cotizaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservas',
            name='id',
        ),
        migrations.AddField(
            model_name='reservas',
            name='reserva_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='id_venta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
