# Generated by Django 6.0.2 on 2026-05-07 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comercial', '0004_remove_reservas_id_reservas_reserva_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservas',
            old_name='reserva_id',
            new_name='id_reserva',
        ),
    ]
